In [2]:
import numpy as np

# Numpy DataType

#### create different ndarray
one dimensional array(vector)

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

two dimensional array

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

three dimensional array

In [6]:
d = np.array([[1, 2, 3], [4, 5, 6]])
e = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([d,e])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

##### ndim
return dimensional array.

In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
c.ndim

3

##### shape
Return the shape of an array.

In [13]:
a

array([1, 2, 3])

In [10]:
a.shape

(3,)

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [15]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [12]:
c.shape

(2, 2, 3)

##### dtype
Type of the data

In [16]:
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('int32')

In [18]:
c.dtype

dtype('int32')

##### size
number of data

In [19]:
a.size

3

In [20]:
b.size

6

In [21]:
c.size

12

# Create Arrays

### Arange

In [4]:
arange_array = np.arange(0, 21, 2)
arange_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Linspace

In [5]:
linspace_array = np.linspace(0, 20, 5)
linspace_array

array([ 0.,  5., 10., 15., 20.])

In [8]:
linspace_array2 = np.linspace(0, 20, 5,retstep=True)
linspace_array2

(array([ 0.,  5., 10., 15., 20.]), 5.0)

In [9]:
linspace_array3 = np.linspace(0, 20, 8, retstep=True)
linspace_array3

(array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
        14.28571429, 17.14285714, 20.        ]),
 2.857142857142857)

### Ones

In [11]:
ones_array = np.ones((3,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
ones_array2 = np.ones((2,3,4), dtype=int)
ones_array2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### Zeros

In [13]:
zero_array = np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Random

In [14]:
random_array = np.random.random(size=(3,4))
random_array

array([[0.96234101, 0.36930471, 0.58616163, 0.80885879],
       [0.19166519, 0.68288441, 0.16148466, 0.95260143],
       [0.39919586, 0.84518753, 0.98063847, 0.16984164]])

In [16]:
random_array2 = np.random.randint(1, 11, (4,3), dtype=int)
random_array2

array([[ 5,  8,  4],
       [10,  9, 10],
       [ 3,  5,  8],
       [ 9, 10,  7]])

### Seed
save firs time random genarete

In [18]:
np.random.seed(1)
seed_array = np.random.randint(1,9,(4,3))
seed_array

array([[6, 4, 5],
       [1, 8, 2],
       [4, 6, 8],
       [1, 1, 2]])