In [1]:
import numpy as np

# Numpy DataType

#### create different ndarray
one dimensional array(vector)

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

two dimensional array

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

three dimensional array

In [6]:
d = np.array([[1, 2, 3], [4, 5, 6]])
e = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([d,e])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

##### ndim
return dimensional array.

In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
c.ndim

3

##### shape
Return the shape of an array.

In [13]:
a

array([1, 2, 3])

In [10]:
a.shape

(3,)

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [15]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [12]:
c.shape

(2, 2, 3)

##### dtype
Type of the data

In [16]:
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('int32')

In [18]:
c.dtype

dtype('int32')

##### size
number of data

In [19]:
a.size

3

In [20]:
b.size

6

In [21]:
c.size

12

# Create Arrays

### Arange

In [4]:
arange_array = np.arange(0, 21, 2)
arange_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Linspace

In [5]:
linspace_array = np.linspace(0, 20, 5)
linspace_array

array([ 0.,  5., 10., 15., 20.])

In [8]:
linspace_array2 = np.linspace(0, 20, 5,retstep=True)
linspace_array2

(array([ 0.,  5., 10., 15., 20.]), 5.0)

In [9]:
linspace_array3 = np.linspace(0, 20, 8, retstep=True)
linspace_array3

(array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
        14.28571429, 17.14285714, 20.        ]),
 2.857142857142857)

### Ones

In [11]:
ones_array = np.ones((3,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
ones_array2 = np.ones((2,3,4), dtype=int)
ones_array2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### Zeros

In [13]:
zero_array = np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Random

In [14]:
random_array = np.random.random(size=(3,4))
random_array

array([[0.96234101, 0.36930471, 0.58616163, 0.80885879],
       [0.19166519, 0.68288441, 0.16148466, 0.95260143],
       [0.39919586, 0.84518753, 0.98063847, 0.16984164]])

In [16]:
random_array2 = np.random.randint(1, 11, (4,3), dtype=int)
random_array2

array([[ 5,  8,  4],
       [10,  9, 10],
       [ 3,  5,  8],
       [ 9, 10,  7]])

### Seed
save firs time random genarete

In [18]:
np.random.seed(1)
seed_array = np.random.randint(1,9,(4,3))
seed_array

array([[6, 4, 5],
       [1, 8, 2],
       [4, 6, 8],
       [1, 1, 2]])

# Index And Slicing

In [19]:
ar = np.arange(1,16)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
ar[0]

1

In [21]:
ar[-5]

11

In [22]:
ar[2] = 150
ar

array([  1,   2, 150,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [23]:
ar2 = np.arange(1,21)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
ar2.shape = (4, 5)
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
ar2[1]

array([ 6,  7,  8,  9, 10])

In [27]:
ar2[1][2]

8

In [28]:
ar2[1,2]

8

In [29]:
ar2[:, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [30]:
ar3 = np.random.randint(1, 9, size=(2, 3, 4))
ar3

array([[[5, 8, 6, 5],
        [7, 2, 3, 5],
        [7, 6, 3, 5]],

       [[4, 5, 3, 5],
        [6, 7, 3, 5],
        [8, 8, 2, 2]]])

In [31]:
ar3[0]

array([[5, 8, 6, 5],
       [7, 2, 3, 5],
       [7, 6, 3, 5]])

In [32]:
ar3[0][1]

array([7, 2, 3, 5])

In [33]:
ar3[0][1][-1]

5

In [35]:
ar3[1, 1, 2]

3

In [36]:
ar3[:, :, -2:]

array([[[6, 5],
        [3, 5],
        [3, 5]],

       [[3, 5],
        [3, 5],
        [2, 2]]])

# Masked Array

In [37]:
ary = np.random.randint(1,100,60)
ary

array([95, 97, 87, 14, 10,  8, 64, 62, 23, 58,  2,  1, 61, 82,  9, 89, 14,
       48, 73, 31, 72,  4, 71, 22, 50, 58,  4, 69, 25, 44, 77, 27, 53, 81,
       42, 83, 16, 65, 69, 26, 99, 88,  8, 27, 26, 23, 10, 68, 24, 28, 38,
       58, 84, 39,  9, 33, 35, 11, 24, 16])

In [39]:
ary.shape

(60,)

In [41]:
ary = ary.reshape((2,5,6))
ary

array([[[95, 97, 87, 14, 10,  8],
        [64, 62, 23, 58,  2,  1],
        [61, 82,  9, 89, 14, 48],
        [73, 31, 72,  4, 71, 22],
        [50, 58,  4, 69, 25, 44]],

       [[77, 27, 53, 81, 42, 83],
        [16, 65, 69, 26, 99, 88],
        [ 8, 27, 26, 23, 10, 68],
        [24, 28, 38, 58, 84, 39],
        [ 9, 33, 35, 11, 24, 16]]])

In [43]:
unique_array = np.unique(ary)
unique_array

array([ 1,  2,  4,  8,  9, 10, 11, 14, 16, 22, 23, 24, 25, 26, 27, 28, 31,
       33, 35, 38, 39, 42, 44, 48, 50, 53, 58, 61, 62, 64, 65, 68, 69, 71,
       72, 73, 77, 81, 82, 83, 84, 87, 88, 89, 95, 97, 99])

In [44]:
ary[ary > 30]

array([95, 97, 87, 64, 62, 58, 61, 82, 89, 48, 73, 31, 72, 71, 50, 58, 69,
       44, 77, 53, 81, 42, 83, 65, 69, 99, 88, 68, 38, 58, 84, 39, 33, 35])

In [47]:
greater_than_30 = ary > 30
greater_than_30

array([[[ True,  True,  True, False, False, False],
        [ True,  True, False,  True, False, False],
        [ True,  True, False,  True, False,  True],
        [ True,  True,  True, False,  True, False],
        [ True,  True, False,  True, False,  True]],

       [[ True, False,  True,  True,  True,  True],
        [False,  True,  True, False,  True,  True],
        [False, False, False, False, False,  True],
        [False, False,  True,  True,  True,  True],
        [False,  True,  True, False, False, False]]])

In [48]:
ary[greater_than_30]

array([95, 97, 87, 64, 62, 58, 61, 82, 89, 48, 73, 31, 72, 71, 50, 58, 69,
       44, 77, 53, 81, 42, 83, 65, 69, 99, 88, 68, 38, 58, 84, 39, 33, 35])

In [51]:
even_elements = ary % 2 ==0
even_elements

array([[[False, False, False,  True,  True,  True],
        [ True,  True, False,  True,  True, False],
        [False,  True, False, False,  True,  True],
        [False, False,  True,  True, False,  True],
        [ True,  True,  True, False, False,  True]],

       [[False, False, False, False,  True, False],
        [ True, False, False,  True, False,  True],
        [ True, False,  True, False,  True,  True],
        [ True,  True,  True,  True,  True, False],
        [False, False, False, False,  True,  True]]])

In [52]:
final_mask = np.logical_and(greater_than_30,even_elements)
ary[final_mask]

array([64, 62, 58, 82, 48, 72, 50, 58, 44, 42, 88, 68, 38, 58, 84])

In [55]:
less_than_20 = ary < 20
result = np.logical_or(greater_than_30,less_than_20)
ary[result]

array([95, 97, 87, 14, 10,  8, 64, 62, 58,  2,  1, 61, 82,  9, 89, 14, 48,
       73, 31, 72,  4, 71, 50, 58,  4, 69, 44, 77, 53, 81, 42, 83, 16, 65,
       69, 99, 88,  8, 10, 68, 38, 58, 84, 39,  9, 33, 35, 11, 16])

# Numpy Broadcasting

In [2]:
arry = np.arange(5)
arry

array([0, 1, 2, 3, 4])

In [3]:
arry + 4

array([4, 5, 6, 7, 8])

In [4]:
arry2 = np.random.randint(1, 9, size = 5).reshape((1,5))
arry2

array([[2, 7, 3, 2, 4]])

In [5]:
arry + arry2

array([[2, 8, 5, 5, 8]])

In [7]:
arry - arry2

array([[-2, -6, -1,  1,  0]])

In [8]:
arry * arry2

array([[ 0,  7,  6,  6, 16]])

In [9]:
arry / arry2

array([[0.        , 0.14285714, 0.66666667, 1.5       , 1.        ]])

In [10]:
arry % arry2

array([[0, 1, 2, 1, 0]], dtype=int32)

In [11]:
arry // arry2

array([[0, 0, 0, 1, 1]], dtype=int32)

In [12]:
arry3 = np.random.randint(1, 99, size=50).reshape((5,10))
arry3

array([[23, 87, 97, 81, 64, 50, 64, 92, 67, 89],
       [55, 65, 24, 60, 55, 53, 16, 73,  1, 29],
       [65, 94, 87, 21, 23, 59, 81, 15, 96, 32],
       [98, 83, 61, 80, 74, 31,  2,  8, 21, 66],
       [60, 19, 52, 97, 16, 31, 47, 16, 35, 52]])

In [13]:
arry2

array([[2, 7, 3, 2, 4]])

In [14]:
arry2 + arry3

ValueError: operands could not be broadcast together with shapes (1,5) (5,10) 

In [15]:
arry3 = np.random.randint(1, 99, size=50).reshape((10,5))
arry3

array([[78, 20, 92, 50, 53],
       [50, 23, 37, 97,  4],
       [58, 59,  9, 53, 97],
       [89, 51, 79, 33, 51],
       [72, 72, 27, 75, 53],
       [25,  6, 59, 39, 84],
       [92, 39, 45, 84, 16],
       [36, 14, 92, 76, 86],
       [83, 74, 92, 26,  3],
       [92, 23, 51, 89, 69]])

###### arry2 = (1,5) => (10,5)

In [16]:
arry2 + arry3

array([[ 80,  27,  95,  52,  57],
       [ 52,  30,  40,  99,   8],
       [ 60,  66,  12,  55, 101],
       [ 91,  58,  82,  35,  55],
       [ 74,  79,  30,  77,  57],
       [ 27,  13,  62,  41,  88],
       [ 94,  46,  48,  86,  20],
       [ 38,  21,  95,  78,  90],
       [ 85,  81,  95,  28,   7],
       [ 94,  30,  54,  91,  73]])

In [17]:
arry2

array([[2, 7, 3, 2, 4]])

In [18]:
q = np.arange(5).reshape(5,1)
q

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [19]:
arry2 + q

array([[ 2,  7,  3,  2,  4],
       [ 3,  8,  4,  3,  5],
       [ 4,  9,  5,  4,  6],
       [ 5, 10,  6,  5,  7],
       [ 6, 11,  7,  6,  8]])

In [2]:
e = np.random.randint(1, 99, size=40).reshape((2, 5, 4))
e

array([[[30, 69, 35, 10],
        [39, 21,  6,  7],
        [20, 13, 85, 94],
        [96, 12, 10, 62],
        [73, 35, 95,  8]],

       [[87, 39, 90, 15],
        [37, 71, 40,  7],
        [91, 15, 50, 39],
        [39, 86, 32, 73],
        [ 4, 22, 72, 73]]])

In [3]:
o = np.arange(20).reshape((5, 4))
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
e + o

array([[[ 30,  70,  37,  13],
        [ 43,  26,  12,  14],
        [ 28,  22,  95, 105],
        [108,  25,  24,  77],
        [ 89,  52, 113,  27]],

       [[ 87,  40,  92,  18],
        [ 41,  76,  46,  14],
        [ 99,  24,  60,  50],
        [ 51,  99,  46,  88],
        [ 20,  39,  90,  92]]])

###### mean => average number

In [5]:
np.mean(e)

45.05

###### median => middle number

In [6]:
np.median(e)

39.0

In [7]:
np.max(e)

96

In [8]:
np.min(e)

4

###### var => variance

In [9]:
np.var(e)

942.8474999999999

###### std => standard deviation

In [10]:
np.std(e)

30.70582192353756

In [11]:
np.sqrt(np.var(e))

30.70582192353756

In [12]:
np.sum(e)

1802

In [13]:
np.sum(e)/e.size

45.05

In [15]:
f = np.arange(100)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
sum(f)

4950

### comparison sum in numpy and sum in python

In [17]:
my_array = np.random.randint(1,99,size=1000000)
my_array[:100]

array([34, 17, 28, 54, 24, 57, 84, 74, 51, 90, 51, 36,  8, 61, 18, 17,  3,
       80, 61, 32, 44, 46, 13, 96, 69, 38, 72, 90, 39, 88, 95, 20, 78, 64,
       38,  8, 80, 26, 83, 56, 43, 43, 95, 13, 40, 95, 12, 84, 56, 69, 69,
       28, 64, 39, 54, 31, 97, 50, 86, 45, 49, 29,  7, 21, 18, 82, 88, 94,
       60, 40, 43, 67, 80, 70, 71, 87,  4, 29, 87, 77, 51, 32, 38,  9, 56,
       59, 10, 17,  8, 72, 18, 31, 72, 28, 24, 40, 96, 16, 51, 49])

In [19]:
import datetime
python_start = datetime.datetime.now()
result_python = sum(my_array)
python_end = datetime.datetime.now()
time_python = python_end - python_start 
time_python

datetime.timedelta(microseconds=59003)

In [20]:
np_start = datetime.datetime.now()
result_np = np.sum(my_array)
np_end = datetime.datetime.now()
time_np = np_end - np_start
time_np

datetime.timedelta(microseconds=999)

# Structured Arrays

In [21]:
names = ["Mohammad", "Ali", "Hadi", "Ehsan"]
ages = [20, 15, 25, 28]
cities = ["tehran", "mashhad", "yazd", "tabriz"]

In [22]:
pattern = [("name", "U50"), ("age", "i4"), ("city", "U50")]

In [23]:
array = np.zeros((5), dtype=pattern)
array

array([('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [24]:
array[0] = ("Mohammad", 20, "tehran")
array

array([('Mohammad', 20, 'tehran'), ('',  0, ''), ('',  0, ''),
       ('',  0, ''), ('',  0, '')],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [25]:
array[3] = ("Ali", 15, "mashhad")
array

array([('Mohammad', 20, 'tehran'), ('',  0, ''), ('',  0, ''),
       ('Ali', 15, 'mashhad'), ('',  0, '')],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [26]:
array["age"]

array([20,  0,  0, 15,  0])

In [27]:
array_3d = np.zeros((2,3,4),dtype = pattern)
array_3d

array([[[('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
        [('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
        [('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')]],

       [[('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
        [('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
        [('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')]]],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [28]:
array_3d[1,1,3]= ("Ehsan",29,"saveh")
array_3d

array([[[('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')],
        [('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')],
        [('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')]],

       [[('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')],
        [('',  0, ''), ('',  0, ''), ('',  0, ''),
         ('Ehsan', 29, 'saveh')],
        [('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')]]],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

### record array

In [29]:
record = np.rec.array([("Ehsan",29,"saveh"), ("Ali", 15, "mashhad")], dtype = pattern)
record

rec.array([('Ehsan', 29, 'saveh'), ('Ali', 15, 'mashhad')],
          dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [30]:
record.name

array(['Ehsan', 'Ali'], dtype='<U50')

# Views & Copy

In [31]:
first_array = np.arange(1, 25).reshape(2,3,4)
first_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [32]:
second_array = first_array
second_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [33]:
first_array == second_array

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [34]:
first_array is second_array

True

###### shallow copy

In [35]:
third_array = first_array.view()
third_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [36]:
third_array == first_array

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [37]:
third_array is first_array

False

In [38]:
id(first_array), id(third_array)

(1608977092848, 1608977092944)

In [39]:
first_array[0, 0, 0]=500
first_array

array([[[500,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [40]:
third_array

array([[[500,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [42]:
forth_array = np.copy(first_array)
forth_array

array([[[500,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

# Add And Remove Elements From Array

In [43]:
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x = np.append(z, [10,12])
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])

In [46]:
v = np.random.randint(1,99,size=24).reshape(2,3,4)
v

array([[[23, 60, 32, 49],
        [62, 49, 17,  7],
        [74, 12, 46, 20]],

       [[91, 87, 47, 70],
        [75, 63, 56, 50],
        [ 1, 55,  2, 33]]])

In [49]:
n = np.random.randint(1, 99, size=24).reshape(2,3,4)
m = np.append(v,n,axis=0)
m

array([[[23, 60, 32, 49],
        [62, 49, 17,  7],
        [74, 12, 46, 20]],

       [[91, 87, 47, 70],
        [75, 63, 56, 50],
        [ 1, 55,  2, 33]],

       [[10, 32, 31,  9],
        [82, 27, 38, 73],
        [82, 95, 77, 88]],

       [[34, 93, 38, 79],
        [31, 32, 58, 56],
        [20, 18, 67, 22]]])

In [50]:
n = np.random.randint(1, 99, size=24).reshape(2,3,4)
m = np.append(v,n,axis=1)
m

array([[[23, 60, 32, 49],
        [62, 49, 17,  7],
        [74, 12, 46, 20],
        [ 7, 19, 11, 43],
        [94, 60, 77, 75],
        [53, 88, 30, 13]],

       [[91, 87, 47, 70],
        [75, 63, 56, 50],
        [ 1, 55,  2, 33],
        [56, 83, 82, 53],
        [29, 82, 61, 42],
        [79, 62, 40,  1]]])

In [52]:
n = np.random.randint(1, 99, size=24).reshape(2,3,4)
m = np.append(v,n,axis=2)
m

array([[[23, 60, 32, 49, 29, 16,  9, 93],
        [62, 49, 17,  7, 32, 54, 79, 43],
        [74, 12, 46, 20, 54, 48, 12, 62]],

       [[91, 87, 47, 70,  9, 37, 41, 87],
        [75, 63, 56, 50, 89, 51, 90, 59],
        [ 1, 55,  2, 33, 24, 48, 42, 49]]])

In [53]:
h = np.insert(v,0,10,axis=0)
h

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[23, 60, 32, 49],
        [62, 49, 17,  7],
        [74, 12, 46, 20]],

       [[91, 87, 47, 70],
        [75, 63, 56, 50],
        [ 1, 55,  2, 33]]])

In [54]:
h = np.insert(v,0,10,axis=1)
h

array([[[10, 10, 10, 10],
        [23, 60, 32, 49],
        [62, 49, 17,  7],
        [74, 12, 46, 20]],

       [[10, 10, 10, 10],
        [91, 87, 47, 70],
        [75, 63, 56, 50],
        [ 1, 55,  2, 33]]])

In [55]:
h = np.insert(v,0,10,axis=2)
h

array([[[10, 23, 60, 32, 49],
        [10, 62, 49, 17,  7],
        [10, 74, 12, 46, 20]],

       [[10, 91, 87, 47, 70],
        [10, 75, 63, 56, 50],
        [10,  1, 55,  2, 33]]])

In [57]:
h = np.insert(v,0,[1,2,3],axis=2)
h

array([[[ 1, 23, 60, 32, 49],
        [ 2, 62, 49, 17,  7],
        [ 3, 74, 12, 46, 20]],

       [[ 1, 91, 87, 47, 70],
        [ 2, 75, 63, 56, 50],
        [ 3,  1, 55,  2, 33]]])

In [58]:
h = np.insert(v,2,[1,2,3],axis=2)
h

array([[[23, 60,  1, 32, 49],
        [62, 49,  2, 17,  7],
        [74, 12,  3, 46, 20]],

       [[91, 87,  1, 47, 70],
        [75, 63,  2, 56, 50],
        [ 1, 55,  3,  2, 33]]])

In [59]:
g = np.empty((2,3,4))
g

array([[[7.94923134e-312, 7.93626426e-312, 7.94923134e-312,
         5.41495948e-321],
        [7.94923134e-312, 7.93626426e-312, 7.94923134e-312,
         5.41990013e-321],
        [7.94923134e-312, 6.01346930e-154, 7.94923134e-312,
         3.60739290e-313]],

       [[7.94923134e-312, 7.41098469e-323, 7.94923134e-312,
         1.11784438e+253],
        [7.94923134e-312, 7.49229304e+247, 7.94923134e-312,
         9.88131292e-323],
        [7.94889030e-312, 0.00000000e+000, 0.00000000e+000,
         7.21478569e-313]]])

In [60]:
np.copyto(g,v)
g

array([[[23., 60., 32., 49.],
        [62., 49., 17.,  7.],
        [74., 12., 46., 20.]],

       [[91., 87., 47., 70.],
        [75., 63., 56., 50.],
        [ 1., 55.,  2., 33.]]])

In [62]:
v

array([[[23, 60, 32, 49],
        [62, 49, 17,  7],
        [74, 12, 46, 20]],

       [[91, 87, 47, 70],
        [75, 63, 56, 50],
        [ 1, 55,  2, 33]]])

In [61]:
w = np.delete(v, 0, axis=0)
w

array([[[91, 87, 47, 70],
        [75, 63, 56, 50],
        [ 1, 55,  2, 33]]])

# Join & Split Arrays

In [63]:
a=np.arange(12).reshape((3,4))
b=np.arange(13,25).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [65]:
result0 = np.concatenate((a,b),axis=0)
result0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [66]:
result1 = np.concatenate((a,b),axis=1)
result1

array([[ 0,  1,  2,  3, 13, 14, 15, 16],
       [ 4,  5,  6,  7, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 21, 22, 23, 24]])

In [68]:
stack0 = np.stack((a, b),axis=0)
stack1 = np.stack((a,b),axis=1)
stack2 = np.stack((a, b),axis=2)

In [69]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [71]:
stack0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [72]:
stack1

array([[[ 0,  1,  2,  3],
        [13, 14, 15, 16]],

       [[ 4,  5,  6,  7],
        [17, 18, 19, 20]],

       [[ 8,  9, 10, 11],
        [21, 22, 23, 24]]])

In [73]:
stack2

array([[[ 0, 13],
        [ 1, 14],
        [ 2, 15],
        [ 3, 16]],

       [[ 4, 17],
        [ 5, 18],
        [ 6, 19],
        [ 7, 20]],

       [[ 8, 21],
        [ 9, 22],
        [10, 23],
        [11, 24]]])

In [74]:
e = np.random.randint(1,99,size=40).reshape(4,2,5)
e

array([[[20, 25, 28, 49, 93],
        [24, 20, 26, 30, 74]],

       [[63, 17, 86, 87,  3],
        [81, 81, 89, 54, 61]],

       [[80, 52, 92, 87, 92],
        [16, 81, 85,  5, 71]],

       [[75, 77, 45, 96, 59],
        [53, 67, 51, 97, 19]]])

In [75]:
split0 = np.split(e, 1, axis=0)
split0

[array([[[20, 25, 28, 49, 93],
         [24, 20, 26, 30, 74]],
 
        [[63, 17, 86, 87,  3],
         [81, 81, 89, 54, 61]],
 
        [[80, 52, 92, 87, 92],
         [16, 81, 85,  5, 71]],
 
        [[75, 77, 45, 96, 59],
         [53, 67, 51, 97, 19]]])]

In [77]:
split01=np.split(e,4,axis=0)
split01

[array([[[20, 25, 28, 49, 93],
         [24, 20, 26, 30, 74]]]),
 array([[[63, 17, 86, 87,  3],
         [81, 81, 89, 54, 61]]]),
 array([[[80, 52, 92, 87, 92],
         [16, 81, 85,  5, 71]]]),
 array([[[75, 77, 45, 96, 59],
         [53, 67, 51, 97, 19]]])]

In [78]:
split1 = np.split(e,1,axis=1)
split1

[array([[[20, 25, 28, 49, 93],
         [24, 20, 26, 30, 74]],
 
        [[63, 17, 86, 87,  3],
         [81, 81, 89, 54, 61]],
 
        [[80, 52, 92, 87, 92],
         [16, 81, 85,  5, 71]],
 
        [[75, 77, 45, 96, 59],
         [53, 67, 51, 97, 19]]])]

In [80]:
split11 = np.split(e,2,axis=1)
split11

[array([[[20, 25, 28, 49, 93]],
 
        [[63, 17, 86, 87,  3]],
 
        [[80, 52, 92, 87, 92]],
 
        [[75, 77, 45, 96, 59]]]),
 array([[[24, 20, 26, 30, 74]],
 
        [[81, 81, 89, 54, 61]],
 
        [[16, 81, 85,  5, 71]],
 
        [[53, 67, 51, 97, 19]]])]

In [81]:
split2 = np.split(e,1,axis=2)
split2

[array([[[20, 25, 28, 49, 93],
         [24, 20, 26, 30, 74]],
 
        [[63, 17, 86, 87,  3],
         [81, 81, 89, 54, 61]],
 
        [[80, 52, 92, 87, 92],
         [16, 81, 85,  5, 71]],
 
        [[75, 77, 45, 96, 59],
         [53, 67, 51, 97, 19]]])]

In [83]:
split22 = np.split(e,5,axis=2)
split22

[array([[[20],
         [24]],
 
        [[63],
         [81]],
 
        [[80],
         [16]],
 
        [[75],
         [53]]]),
 array([[[25],
         [20]],
 
        [[17],
         [81]],
 
        [[52],
         [81]],
 
        [[77],
         [67]]]),
 array([[[28],
         [26]],
 
        [[86],
         [89]],
 
        [[92],
         [85]],
 
        [[45],
         [51]]]),
 array([[[49],
         [30]],
 
        [[87],
         [54]],
 
        [[87],
         [ 5]],
 
        [[96],
         [97]]]),
 array([[[93],
         [74]],
 
        [[ 3],
         [61]],
 
        [[92],
         [71]],
 
        [[59],
         [19]]])]

# Array Sorting And Views

In [84]:
my_array = np.arange(24)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### shape vs reshape

In [85]:
my_array.shape = (2, 3, 4)
my_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [86]:
reshape_array = my_array.reshape((2,12))
reshape_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [87]:
reshape_array[0,0]=1234
reshape_array

array([[1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11],
       [  12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
          23]])

In [88]:
my_array

array([[[1234,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

###### ravel , flatten
returt array in vector

In [89]:
ravel_array=np.ravel(my_array)
ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [91]:
flatten_array = my_array.flatten()
flatten_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [93]:
ravel_array[1]=144
ravel_array

array([1234,  144,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [94]:
my_array

array([[[1234,  144,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [95]:
flatten_array[2]=1444
flatten_array

array([1234,    1, 1444,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [96]:
my_array

array([[[1234,  144,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [97]:
flat_array = list(my_array.flat)
flat_array

[1234,
 144,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23]

In [98]:
my_array

array([[[1234,  144,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [99]:
my_array.shape = (4, 6)
my_array[0,0]=0
my_array[0,1]=1
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [100]:
my_3d_array = np.arange(24).reshape((2,3,4))
my_3d_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

###### fliplr
left to right

In [101]:
np.fliplr(my_array)

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18]])

In [102]:
np.fliplr(my_3d_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

###### flipud
up to down

In [103]:
np.flipud(my_array)

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [104]:
np.flipud(my_3d_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

###### roll

In [105]:
np.roll(my_array,2)

array([[22, 23,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [106]:
np.roll(my_3d_array,5)

array([[[19, 20, 21, 22],
        [23,  0,  1,  2],
        [ 3,  4,  5,  6]],

       [[ 7,  8,  9, 10],
        [11, 12, 13, 14],
        [15, 16, 17, 18]]])

In [107]:
np.rot90(my_array)

array([[ 5, 11, 17, 23],
       [ 4, 10, 16, 22],
       [ 3,  9, 15, 21],
       [ 2,  8, 14, 20],
       [ 1,  7, 13, 19],
       [ 0,  6, 12, 18]])

In [108]:
np.rot90(my_array,k=-1)

array([[18, 12,  6,  0],
       [19, 13,  7,  1],
       [20, 14,  8,  2],
       [21, 15,  9,  3],
       [22, 16, 10,  4],
       [23, 17, 11,  5]])

# Transpose

In [2]:
my_vector = np.arange(6)
my_2d_array = np.arange(12).reshape((3, 4))
my_3d_array = np.arange(24).reshape((2, 3, 4))

In [3]:
my_vector

array([0, 1, 2, 3, 4, 5])

In [4]:
my_2d_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
my_3d_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
my_vector.shape

(6,)

In [7]:
np.transpose(my_vector)

array([0, 1, 2, 3, 4, 5])

In [9]:
my_vector.shape = (1,6)
my_vector

array([[0, 1, 2, 3, 4, 5]])

In [10]:
my_vector.shape

(1, 6)

In [11]:
np.transpose(my_vector)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
np.transpose(my_2d_array)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [13]:
result = np.transpose(my_3d_array, axes=(0,1,2))
result

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
my_3d_array.shape , result.shape

((2, 3, 4), (2, 3, 4))

In [15]:
result = np.transpose(my_3d_array, axes=(2,0,1))
result

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [16]:
my_3d_array.shape , result.shape

((2, 3, 4), (4, 2, 3))

In [18]:
my_3d_array.shape , np.swapaxes(my_3d_array,1,0 ).shape

((2, 3, 4), (3, 2, 4))

In [19]:
my_3d_array.shape , np.swapaxes(my_3d_array,2,0 ).shape

((2, 3, 4), (4, 3, 2))

In [20]:
move =  np.moveaxis(my_3d_array,2,0)
move

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [21]:
move.shape, my_3d_array.shape

((4, 2, 3), (2, 3, 4))

# Dot Product

In [22]:
a = np.random.randint(0,99,size=(3,4))
b = np.random.randint(0, 99, size = (3,4))

In [23]:
a

array([[21, 26, 95, 65],
       [87, 41, 50, 81],
       [73, 51, 27, 77]])

In [24]:
b

array([[85,  2, 35, 69],
       [64, 37, 96, 89],
       [95, 76,  6, 62]])

In [25]:
a*b

array([[1785,   52, 3325, 4485],
       [5568, 1517, 4800, 7209],
       [6935, 3876,  162, 4774]])

In [26]:
c = np.dot(a,b)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [27]:
c = np.dot(a, b.T)
c

array([[ 9647, 17211,  8571],
       [14816, 19094, 16703],
       [12565, 16004, 15747]])