In [1]:
import numpy as np

# Numpy DataType

#### create different ndarray
one dimensional array(vector)

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

two dimensional array

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

three dimensional array

In [6]:
d = np.array([[1, 2, 3], [4, 5, 6]])
e = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([d,e])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

##### ndim
return dimensional array.

In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
c.ndim

3

##### shape
Return the shape of an array.

In [13]:
a

array([1, 2, 3])

In [10]:
a.shape

(3,)

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [15]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [12]:
c.shape

(2, 2, 3)

##### dtype
Type of the data

In [16]:
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('int32')

In [18]:
c.dtype

dtype('int32')

##### size
number of data

In [19]:
a.size

3

In [20]:
b.size

6

In [21]:
c.size

12

# Create Arrays

### Arange

In [4]:
arange_array = np.arange(0, 21, 2)
arange_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Linspace

In [5]:
linspace_array = np.linspace(0, 20, 5)
linspace_array

array([ 0.,  5., 10., 15., 20.])

In [8]:
linspace_array2 = np.linspace(0, 20, 5,retstep=True)
linspace_array2

(array([ 0.,  5., 10., 15., 20.]), 5.0)

In [9]:
linspace_array3 = np.linspace(0, 20, 8, retstep=True)
linspace_array3

(array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
        14.28571429, 17.14285714, 20.        ]),
 2.857142857142857)

### Ones

In [11]:
ones_array = np.ones((3,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
ones_array2 = np.ones((2,3,4), dtype=int)
ones_array2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### Zeros

In [13]:
zero_array = np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Random

In [14]:
random_array = np.random.random(size=(3,4))
random_array

array([[0.96234101, 0.36930471, 0.58616163, 0.80885879],
       [0.19166519, 0.68288441, 0.16148466, 0.95260143],
       [0.39919586, 0.84518753, 0.98063847, 0.16984164]])

In [16]:
random_array2 = np.random.randint(1, 11, (4,3), dtype=int)
random_array2

array([[ 5,  8,  4],
       [10,  9, 10],
       [ 3,  5,  8],
       [ 9, 10,  7]])

### Seed
save firs time random genarete

In [18]:
np.random.seed(1)
seed_array = np.random.randint(1,9,(4,3))
seed_array

array([[6, 4, 5],
       [1, 8, 2],
       [4, 6, 8],
       [1, 1, 2]])

# Index And Slicing

In [19]:
ar = np.arange(1,16)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
ar[0]

1

In [21]:
ar[-5]

11

In [22]:
ar[2] = 150
ar

array([  1,   2, 150,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [23]:
ar2 = np.arange(1,21)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
ar2.shape = (4, 5)
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
ar2[1]

array([ 6,  7,  8,  9, 10])

In [27]:
ar2[1][2]

8

In [28]:
ar2[1,2]

8

In [29]:
ar2[:, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [30]:
ar3 = np.random.randint(1, 9, size=(2, 3, 4))
ar3

array([[[5, 8, 6, 5],
        [7, 2, 3, 5],
        [7, 6, 3, 5]],

       [[4, 5, 3, 5],
        [6, 7, 3, 5],
        [8, 8, 2, 2]]])

In [31]:
ar3[0]

array([[5, 8, 6, 5],
       [7, 2, 3, 5],
       [7, 6, 3, 5]])

In [32]:
ar3[0][1]

array([7, 2, 3, 5])

In [33]:
ar3[0][1][-1]

5

In [35]:
ar3[1, 1, 2]

3

In [36]:
ar3[:, :, -2:]

array([[[6, 5],
        [3, 5],
        [3, 5]],

       [[3, 5],
        [3, 5],
        [2, 2]]])

# Masked Array

In [37]:
ary = np.random.randint(1,100,60)
ary

array([95, 97, 87, 14, 10,  8, 64, 62, 23, 58,  2,  1, 61, 82,  9, 89, 14,
       48, 73, 31, 72,  4, 71, 22, 50, 58,  4, 69, 25, 44, 77, 27, 53, 81,
       42, 83, 16, 65, 69, 26, 99, 88,  8, 27, 26, 23, 10, 68, 24, 28, 38,
       58, 84, 39,  9, 33, 35, 11, 24, 16])

In [39]:
ary.shape

(60,)

In [41]:
ary = ary.reshape((2,5,6))
ary

array([[[95, 97, 87, 14, 10,  8],
        [64, 62, 23, 58,  2,  1],
        [61, 82,  9, 89, 14, 48],
        [73, 31, 72,  4, 71, 22],
        [50, 58,  4, 69, 25, 44]],

       [[77, 27, 53, 81, 42, 83],
        [16, 65, 69, 26, 99, 88],
        [ 8, 27, 26, 23, 10, 68],
        [24, 28, 38, 58, 84, 39],
        [ 9, 33, 35, 11, 24, 16]]])

In [43]:
unique_array = np.unique(ary)
unique_array

array([ 1,  2,  4,  8,  9, 10, 11, 14, 16, 22, 23, 24, 25, 26, 27, 28, 31,
       33, 35, 38, 39, 42, 44, 48, 50, 53, 58, 61, 62, 64, 65, 68, 69, 71,
       72, 73, 77, 81, 82, 83, 84, 87, 88, 89, 95, 97, 99])

In [44]:
ary[ary > 30]

array([95, 97, 87, 64, 62, 58, 61, 82, 89, 48, 73, 31, 72, 71, 50, 58, 69,
       44, 77, 53, 81, 42, 83, 65, 69, 99, 88, 68, 38, 58, 84, 39, 33, 35])

In [47]:
greater_than_30 = ary > 30
greater_than_30

array([[[ True,  True,  True, False, False, False],
        [ True,  True, False,  True, False, False],
        [ True,  True, False,  True, False,  True],
        [ True,  True,  True, False,  True, False],
        [ True,  True, False,  True, False,  True]],

       [[ True, False,  True,  True,  True,  True],
        [False,  True,  True, False,  True,  True],
        [False, False, False, False, False,  True],
        [False, False,  True,  True,  True,  True],
        [False,  True,  True, False, False, False]]])

In [48]:
ary[greater_than_30]

array([95, 97, 87, 64, 62, 58, 61, 82, 89, 48, 73, 31, 72, 71, 50, 58, 69,
       44, 77, 53, 81, 42, 83, 65, 69, 99, 88, 68, 38, 58, 84, 39, 33, 35])

In [51]:
even_elements = ary % 2 ==0
even_elements

array([[[False, False, False,  True,  True,  True],
        [ True,  True, False,  True,  True, False],
        [False,  True, False, False,  True,  True],
        [False, False,  True,  True, False,  True],
        [ True,  True,  True, False, False,  True]],

       [[False, False, False, False,  True, False],
        [ True, False, False,  True, False,  True],
        [ True, False,  True, False,  True,  True],
        [ True,  True,  True,  True,  True, False],
        [False, False, False, False,  True,  True]]])

In [52]:
final_mask = np.logical_and(greater_than_30,even_elements)
ary[final_mask]

array([64, 62, 58, 82, 48, 72, 50, 58, 44, 42, 88, 68, 38, 58, 84])

In [55]:
less_than_20 = ary < 20
result = np.logical_or(greater_than_30,less_than_20)
ary[result]

array([95, 97, 87, 14, 10,  8, 64, 62, 58,  2,  1, 61, 82,  9, 89, 14, 48,
       73, 31, 72,  4, 71, 50, 58,  4, 69, 44, 77, 53, 81, 42, 83, 16, 65,
       69, 99, 88,  8, 10, 68, 38, 58, 84, 39,  9, 33, 35, 11, 16])

# Numpy Broadcasting

In [2]:
arry = np.arange(5)
arry

array([0, 1, 2, 3, 4])

In [3]:
arry + 4

array([4, 5, 6, 7, 8])

In [4]:
arry2 = np.random.randint(1, 9, size = 5).reshape((1,5))
arry2

array([[2, 7, 3, 2, 4]])

In [5]:
arry + arry2

array([[2, 8, 5, 5, 8]])

In [7]:
arry - arry2

array([[-2, -6, -1,  1,  0]])

In [8]:
arry * arry2

array([[ 0,  7,  6,  6, 16]])

In [9]:
arry / arry2

array([[0.        , 0.14285714, 0.66666667, 1.5       , 1.        ]])

In [10]:
arry % arry2

array([[0, 1, 2, 1, 0]], dtype=int32)

In [11]:
arry // arry2

array([[0, 0, 0, 1, 1]], dtype=int32)

In [12]:
arry3 = np.random.randint(1, 99, size=50).reshape((5,10))
arry3

array([[23, 87, 97, 81, 64, 50, 64, 92, 67, 89],
       [55, 65, 24, 60, 55, 53, 16, 73,  1, 29],
       [65, 94, 87, 21, 23, 59, 81, 15, 96, 32],
       [98, 83, 61, 80, 74, 31,  2,  8, 21, 66],
       [60, 19, 52, 97, 16, 31, 47, 16, 35, 52]])

In [13]:
arry2

array([[2, 7, 3, 2, 4]])

In [14]:
arry2 + arry3

ValueError: operands could not be broadcast together with shapes (1,5) (5,10) 

In [15]:
arry3 = np.random.randint(1, 99, size=50).reshape((10,5))
arry3

array([[78, 20, 92, 50, 53],
       [50, 23, 37, 97,  4],
       [58, 59,  9, 53, 97],
       [89, 51, 79, 33, 51],
       [72, 72, 27, 75, 53],
       [25,  6, 59, 39, 84],
       [92, 39, 45, 84, 16],
       [36, 14, 92, 76, 86],
       [83, 74, 92, 26,  3],
       [92, 23, 51, 89, 69]])

###### arry2 = (1,5) => (10,5)

In [16]:
arry2 + arry3

array([[ 80,  27,  95,  52,  57],
       [ 52,  30,  40,  99,   8],
       [ 60,  66,  12,  55, 101],
       [ 91,  58,  82,  35,  55],
       [ 74,  79,  30,  77,  57],
       [ 27,  13,  62,  41,  88],
       [ 94,  46,  48,  86,  20],
       [ 38,  21,  95,  78,  90],
       [ 85,  81,  95,  28,   7],
       [ 94,  30,  54,  91,  73]])

In [17]:
arry2

array([[2, 7, 3, 2, 4]])

In [18]:
q = np.arange(5).reshape(5,1)
q

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [19]:
arry2 + q

array([[ 2,  7,  3,  2,  4],
       [ 3,  8,  4,  3,  5],
       [ 4,  9,  5,  4,  6],
       [ 5, 10,  6,  5,  7],
       [ 6, 11,  7,  6,  8]])

In [2]:
e = np.random.randint(1, 99, size=40).reshape((2, 5, 4))
e

array([[[30, 69, 35, 10],
        [39, 21,  6,  7],
        [20, 13, 85, 94],
        [96, 12, 10, 62],
        [73, 35, 95,  8]],

       [[87, 39, 90, 15],
        [37, 71, 40,  7],
        [91, 15, 50, 39],
        [39, 86, 32, 73],
        [ 4, 22, 72, 73]]])

In [3]:
o = np.arange(20).reshape((5, 4))
o

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
e + o

array([[[ 30,  70,  37,  13],
        [ 43,  26,  12,  14],
        [ 28,  22,  95, 105],
        [108,  25,  24,  77],
        [ 89,  52, 113,  27]],

       [[ 87,  40,  92,  18],
        [ 41,  76,  46,  14],
        [ 99,  24,  60,  50],
        [ 51,  99,  46,  88],
        [ 20,  39,  90,  92]]])

###### mean => average number

In [5]:
np.mean(e)

45.05

###### median => middle number

In [6]:
np.median(e)

39.0

In [7]:
np.max(e)

96

In [8]:
np.min(e)

4

###### var => variance

In [9]:
np.var(e)

942.8474999999999

###### std => standard deviation

In [10]:
np.std(e)

30.70582192353756

In [11]:
np.sqrt(np.var(e))

30.70582192353756

In [12]:
np.sum(e)

1802

In [13]:
np.sum(e)/e.size

45.05

In [15]:
f = np.arange(100)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
sum(f)

4950

### comparison sum in numpy and sum in python

In [17]:
my_array = np.random.randint(1,99,size=1000000)
my_array[:100]

array([34, 17, 28, 54, 24, 57, 84, 74, 51, 90, 51, 36,  8, 61, 18, 17,  3,
       80, 61, 32, 44, 46, 13, 96, 69, 38, 72, 90, 39, 88, 95, 20, 78, 64,
       38,  8, 80, 26, 83, 56, 43, 43, 95, 13, 40, 95, 12, 84, 56, 69, 69,
       28, 64, 39, 54, 31, 97, 50, 86, 45, 49, 29,  7, 21, 18, 82, 88, 94,
       60, 40, 43, 67, 80, 70, 71, 87,  4, 29, 87, 77, 51, 32, 38,  9, 56,
       59, 10, 17,  8, 72, 18, 31, 72, 28, 24, 40, 96, 16, 51, 49])

In [19]:
import datetime
python_start = datetime.datetime.now()
result_python = sum(my_array)
python_end = datetime.datetime.now()
time_python = python_end - python_start 
time_python

datetime.timedelta(microseconds=59003)

In [20]:
np_start = datetime.datetime.now()
result_np = np.sum(my_array)
np_end = datetime.datetime.now()
time_np = np_end - np_start
time_np

datetime.timedelta(microseconds=999)