In [1]:
import numpy as np

#### create different ndarray
one dimensional array(vector)

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

two dimensional array

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

three dimensional array

In [6]:
d = np.array([[1, 2, 3], [4, 5, 6]])
e = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([d,e])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

##### ndim
return dimensional array.

In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
c.ndim

3

##### shape
Return the shape of an array.

In [13]:
a

array([1, 2, 3])

In [10]:
a.shape

(3,)

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [15]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [12]:
c.shape

(2, 2, 3)

##### dtype
Type of the data

In [16]:
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('int32')

In [18]:
c.dtype

dtype('int32')

##### size
number of data

In [19]:
a.size

3

In [20]:
b.size

6

In [21]:
c.size

12